[phases.setup]
nixPkgs = ["python39", "pip"]

[phases.install]
cmds = [
  "pip install --no-cache-dir --upgrade pip",
  "pip install --no-cache-dir torch torchvision --index-url https://download.pytorch.org/whl/cpu",
  "pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = [
  "echo 'Build completed successfully'"
]

[start]
cmd = "gunicorn app_mongodb:app --bind 0.0.0.0:$PORT --timeout 300 --workers 1"
