[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = [
  "pip install --no-cache-dir --upgrade pip",
  "pip install --no-cache-dir torch==2.1.0+cpu torchvision==0.16.0+cpu --index-url https://download.pytorch.org/whl/cpu",
  "pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = [
  "echo 'Build completed successfully'"
]

[start]
cmd = "gunicorn app_mongodb:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120"
