[phases.setup]
nixPkgs = ["python39", "opencv", "ffmpeg", "gcc", "gfortran", "pkg-config", "cmake"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "python app_mongodb.py"
