[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn app_mongodb:app --bind 0.0.0.0:$PORT --timeout 300 --workers 1"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3
healthcheckPath = "/"
healthcheckTimeout = 300