[build]
builder = "nixpacks"
buildCommand = "pip install --no-cache-dir torch torchvision --index-url https://download.pytorch.org/whl/cpu && pip install --no-cache-dir -r requirements.txt"

[deploy]
startCommand = "gunicorn app_mongodb:app --bind 0.0.0.0:$PORT --timeout 300 --workers 1"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckPath = "/"
healthcheckTimeout = 300