[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn app_mongodb:app --bind 0.0.0.0:${PORT:-5000} --workers 1 --timeout 120"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckPath = "/"
healthcheckTimeout = 300
