[build]
builder = "nixpacks"

[deploy]
startCommand = "sh -c 'gunicorn app_mongodb:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckPath = "/"
healthcheckTimeout = 300
